### ISSUE TITLE
请问是否可以实现图片点击放大效果呢？

### ISSUE THREAD

**Issue by TyCoding** [cccyb/hexo-theme-pinghsu#3]
首先感谢作者提供了这个精美的主题，请问是否可以像NexT主题那样，点击图片可以放大呢》

**Comment by cccyb** [comment]
已加入todo list，后续会抽空加上滴~ @TyCoding

**Comment by cccyb** [comment]
@TyCoding 1.4.1版本已添加图片点击放大功能，https://github.com/cccyb/hexo-theme-pinghsu/releases

**Comment by TyCoding** [comment]
> @TyCoding 1.4.1版本已添加图片点击放大功能，https://github.com/cccyb/hexo-theme-pinghsu/releases

 哇咔咔，炒鸡感谢
