### ISSUE TITLE
3个问题

### ISSUE THREAD

**Issue by yyb1995** [cccyb/hexo-theme-pinghsu#4]
首先十分感谢你将pinghsu主题移植到hexo，这个主题真的很好看。不过在使用过程中我发现3个问题。
1. 博客页面右边的超链接无法使用。[示例](https://chenyubo.me/hexo-theme-pinghsu/)。我自己使用时，中文超链接失效，英文正常。我查了一下好像是和URL编解码有关，页面的中文超链接没有进行解码，但我没学过前端所以不太懂233。我看了[另一个博客](https://me.ursb.me/)的处理方法是把超链接全部变成随机数字。我在你的代码里也看到了相关实现。
https://github.com/cccyb/hexo-theme-pinghsu/blob/6062520bd693aa4f00645a423779ec6ae2313546/layout/_partial/footer.ejs#L88
https://github.com/cccyb/hexo-theme-pinghsu/blob/6062520bd693aa4f00645a423779ec6ae2313546/layout/_partial/footer.ejs#L107
但107行可以看出并没有用上随机数。我把107行改为`elem.id = id + guid++; `用chrome调试正常。不过应该也可以直接把中文超链接进行解码。
2. 我看到你也加入了滚动平滑效果。但是返回页首这个箭头是没有平滑效果的，我也不太懂为什么，是`a href="#"`没有id吗？不过我的处理方法是再设了一个`<a id="top" class="anchor-top"></a>`，然后css里面设置`top:0px;`。向上箭头的超链接改为`<a href="#top">`就行。
3. 在设置archive页标题时，如果使用了分页，那么标题就只会统计当前页的博客数。因此这里我觉得改成`site.posts.length`比较好。
https://github.com/cccyb/hexo-theme-pinghsu/blob/6062520bd693aa4f00645a423779ec6ae2313546/layout/archive.ejs#L7
4. 在[archive.ejs](https://github.com/cccyb/hexo-theme-pinghsu/blob/master/layout/archive.ejs)里面没有加入以下分页代码，好像会导致无法正常分页。我看了是在[page-archive.ejs](https://github.com/cccyb/hexo-theme-pinghsu/blob/master/layout/_partial/page-archive.ejs)里加了。不过好像不起作用。
```html
<% if (page.total > 1) { %>
    <div class="lists-navigator clearfix">
    <%- partial('_partial/pagination') %>
    </div>
    <% } %>
```

另外，我自己在你的基础上自己也做了个[博客](https://yyb1995.github.io/)，加入了看板娘和站内搜索，修改了一些无效的分享链接，加了一些简单的特效，欢迎参观~

**Comment by cccyb** [comment]
非常感谢你提出的问题，前段时间工作有点忙，没顾上这边，后续我会抽时间将你说的问题看一下，如果可以，也欢迎你将更多好的功能merge过来，一起建设这个主题~

**Comment by cccyb** [comment]
非常感谢你的修改方案，你提出的问题我都已经参考你的方案进行修复了，见版本[v1.4.2](https://github.com/cccyb/hexo-theme-pinghsu/releases/tag/v1.4.2)

**Comment by yyb1995** [comment]
只是找了一些很小的bug，再次感谢你把这个主题移植到HEXO！
